name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download Script
      run: wget https://raw.githubusercontent.com/SilkArt/spotifyaccgen/master/spotify.sh
    - name: Run Script
      run: bash spotify.sh
    
